package analyzer

import (
	"encoding/json"

	"github.com/rs/zerolog/log"

	"github.com/verifydev/project-analyzer/pkg/signals"
)

// trimForPublish creates a slimmed-down copy of ProjectSignals for RabbitMQ.
//
// The full ProjectSignals struct can be 50-200KB+ due to:
//   - ASTDeepAnalysis (import graphs, pattern arrays)
//   - TechDependencyGraph raw nodes/edges (only summary metrics needed downstream)
//   - ArchitectureGraph (visualization-only, not stored in DB)
//
// The aura-processor only needs:
//   - Core signals (for scoring): folderStructure, codeSignals, languages, frameworks, etc.
//   - IndustryAnalysis (verified skills for DB storage)
//   - IntelligenceVerdict (dimensional scores, trust, verdict for DB)
//   - ConfidenceReport (Bayesian posteriors, ensemble for DB)
//   - TechDependencyGraph summary (stacks, clusters, metrics — NOT raw nodes/edges)
//   - Git forensics & authorship (for DB)
//   - Complexity score (for DB)
//
// This REMOVES:
//   - ASTDeepAnalysis (internal-only, never stored)
//   - ArchitectureGraph (visualization, never stored)
//   - TechDependencyGraph.Nodes[] (raw graph nodes — only metrics stored)
//   - TechDependencyGraph.Edges[] (raw graph edges — only metrics stored)
//   - IndustryAnalysis.SkillsByCategory (redundant — rebuilt from VerifiedSkills)
//   - VerifiedSkill.Keywords (rarely > 5% population rate)
func trimForPublish(full *signals.ProjectSignals) *signals.ProjectSignals {
	slim := *full // shallow copy

	// 0. Nil out forensics — no longer generated by Go engine
	slim.GitForensics = nil
	slim.AuthorshipVerdict = nil

	// 1. Drop ASTDeepAnalysis — internal engine data, aura-processor never reads it
	slim.ASTDeepAnalysis = nil

	// 2. Drop ArchitectureGraph — visualization data, aura-processor never reads it
	slim.ArchitectureGraph = nil

	// 3. Slim TechDependencyGraph — keep summary metrics + stacks/clusters, drop raw nodes/edges
	if full.TechDependencyGraph != nil {
		slimGraph := &signals.TechDependencyGraph{
			// Keep summary metrics (stored in DB)
			TotalNodes:     full.TechDependencyGraph.TotalNodes,
			TotalEdges:     full.TechDependencyGraph.TotalEdges,
			GraphDensity:   full.TechDependencyGraph.GraphDensity,
			AvgNodeWeight:  full.TechDependencyGraph.AvgNodeWeight,
			MaxConnections: full.TechDependencyGraph.MaxConnections,

			// Keep detected stacks (stored in DB as graph_detected_stacks)
			DetectedStacks: full.TechDependencyGraph.DetectedStacks,

			// Keep inferred skills (stored in DB as graph_inferred_skills)
			InferredSkills: full.TechDependencyGraph.InferredSkills,

			// Keep clusters (stored in DB as graph_clusters)
			Clusters: full.TechDependencyGraph.Clusters,

			// DROPPED: Nodes[] and Edges[] — raw graph data never stored by aura-processor
		}
		slim.TechDependencyGraph = slimGraph
	}

	// 4. Slim IndustryAnalysis — drop redundant SkillsByCategory map
	if full.IndustryAnalysis != nil {
		slimIndustry := *full.IndustryAnalysis // shallow copy
		slimIndustry.SkillsByCategory = nil    // rebuilt by consumer if needed

		// Trim keywords, signals, and weight from verified skills (low-value, high-volume)
		if len(slimIndustry.VerifiedSkills) > 0 {
			trimmedSkills := make([]signals.VerifiedSkill, len(slimIndustry.VerifiedSkills))
			for i, skill := range slimIndustry.VerifiedSkills {
				trimmedSkills[i] = skill
				trimmedSkills[i].Keywords = nil // empty keywords to save space
				trimmedSkills[i].Signals = nil  // redundant with top-level infraSignals
				trimmedSkills[i].Weight = 0     // internal scoring only
			}
			slimIndustry.VerifiedSkills = trimmedSkills
		}

		slim.IndustryAnalysis = &slimIndustry
	}

	// 5. Slim ConfidenceReport — drop per-skill likelihood (never stored)
	if full.ConfidenceReport != nil {
		slimConf := *full.ConfidenceReport // shallow copy
		if len(slimConf.SkillConfidences) > 0 {
			trimmedSC := make([]signals.SkillBayesianResult, len(slimConf.SkillConfidences))
			for i, sc := range slimConf.SkillConfidences {
				trimmedSC[i] = sc
				trimmedSC[i].Likelihood = 0 // not stored by consumer
			}
			slimConf.SkillConfidences = trimmedSC
		}
		slim.ConfidenceReport = &slimConf
	}

	// Log size reduction
	fullSize := jsonSize(full)
	slimSize := jsonSize(&slim)
	reduction := float64(fullSize-slimSize) / float64(fullSize) * 100

	log.Info().
		Int("fullBytes", fullSize).
		Int("slimBytes", slimSize).
		Float64("reductionPct", reduction).
		Msg("📦 Trimmed payload for RabbitMQ publish")

	return &slim
}

// jsonSize returns the approximate JSON byte size of a value.
func jsonSize(v interface{}) int {
	data, err := json.Marshal(v)
	if err != nil {
		return 0
	}
	return len(data)
}
